name: HeromcSpawnPlugin
version: '${project.version}'
main: me.asem__1425.heromcspawnplugin.HerocmcSpawnPlugin
authors: [ asem__1425, MrThunder ]
description: HeromcSpawnPlugin
commands:
  spawn:
    description: main command